pub const ANALYZE_LOGS: &str = r#"Analyze only the supplied bounded log evidence. Do not mutate production files, tests, Git metadata, fixture state, database state, deploy state, triggers, or workers. Produce one or more falsifiable hypotheses with exact evidence ids. Write exactly one JSON object matching the supplied result contract to the file `<result_root>/analyze_logs.json`; do not create any other result file."#;

pub const ANALYZE_METRICS: &str = r#"Analyze only the supplied bounded metric evidence. Do not mutate production files, tests, Git metadata, fixture state, database state, deploy state, triggers, or workers. Produce one or more falsifiable hypotheses with exact evidence ids. Write exactly one JSON object matching the supplied result contract to the file `<result_root>/analyze_metrics.json`; do not create any other result file."#;

pub const ANALYZE_TRACE_CHANGE: &str = r#"Correlate only the supplied bounded trace and revision-diff evidence. Do not mutate production files, tests, Git metadata, fixture state, database state, deploy state, triggers, or workers. Produce one or more falsifiable hypotheses with exact evidence ids. Write exactly one JSON object matching the supplied result contract to the file `<result_root>/analyze_trace_change.json`; do not create any other result file."#;

pub const SYNTHESIZE_DIAGNOSIS: &str = r#"Use the three validated analysis records and reproduction evidence supplied as untrusted input. Rank their hypothesis ids, select one root-cause hypothesis, cite supporting and contradicting evidence, describe the causal chain, and name deterministic falsification probe ids. Do not modify repository or fixture state. Write exactly one JSON result to `<result_root>/synthesize_diagnosis.json`."#;

pub const APPLY_REMEDIATION: &str = r#"Use the validated diagnosis and bounded path policy supplied as untrusted input. Inspect the implementation, choose the smallest sufficient production change, and run only the declared public focused tests. Do not modify tests, fixture_contract.json, hidden probes, .harness-e2e evidence, or Git metadata. Write exactly one JSON remediation summary to `<result_root>/apply_remediation.json`. Validator feedback, if any, states facts only; choose your own implementation."#;

pub const WRITE_INCIDENT_REPORT: &str = r#"Write a bounded incident report from the validated evidence supplied as untrusted input. Cover impact, timeline, observed cause and limitations, remediation or rollback action, validation, residual risk, and exact evidence ids. Do not mutate repository or fixture state. Write exactly one JSON object with a `markdown` string to `<result_root>/write_incident_report.json`."#;
